feat(magic): support PRQL query in line magic (#160)
Supports execution of PRQL queries in line magic, like that.

```python
results = %prql from p = `products.csv` | aggregate [min unitsInStock, max unitsInStock]
```

This PR also changes the function that performs argument parsing from
`sql.parse.magic_args` to
`IPython.core.magic_arguments.parse_argstring`.
In SQL we need to use `sql.parse.magic_args` because the comment
character is `--` in SQL. In PRQL, we do not need to consider `--`.
`IPython.core.magic_arguments.parse_argstring` is more strict and will
raise an error for unsupported arguments such as `--foo`.

```default
In [1]: %load_ext pyprql.magic

In [2]: %prql --foo from a
UsageError: unrecognized arguments: --foo
```